module.exports = {
  name: '中台应用',
  list: [{
    name: '客户中心___customerCenter',
    page: 'customerCenter',
    route: 'customerCenter',
  }, {
    name: 'CMS应用',
    page: 'cms',
    route: 'cms',
  }, {
    name: '风控管理___risk-management',
    page: 'risk-management',
    route: 'risk',
  }, {
    name: '支付中心管理___pay-center',
    page: 'pay-center',
    route: 'pay-center',
  }, {
    name: '营销管理___marketingActivities',
    page: 'marketingActivities',
    route: 'marketingActivities',
  }, {
    name: '订单管理___order-management',
    page: 'order-management',
    route: 'orderManagement',
  }, {
    name: '支付/部门管理___business-management',
    page: 'business-management',
    route: 'business-management',
  }, {
    name: 'IM',
    page: 'im',
    route: 'im',
  }, {
    name: 'IM产品',
    page: 'im-product',
    route: 'im-product',
  }]
}
